/* ======================================== Operational Database Exploration ======================================== */
SELECT * FROM MONCITY.FACULTY;
SELECT * FROM MONCITY.RESEARCHCENTER;
SELECT * FROM MONCITY.PASSENGER; -- DONE
SELECT * FROM MONCITY.ERROR;
SELECT * FROM MONCITY.MAINTENANCETYPE;
SELECT * FROM MONCITY.BOOKING;
SELECT * FROM MONCITY.CAR;
SELECT * FROM MONCITY.MAINTENANCE;
SELECT * FROM MONCITY.ACCIDENTINFO;
SELECT * FROM MONCITY.CARACCIDENT;
SELECT * FROM MONCITY.MAINTENANCETEAM;
SELECT * FROM MONCITY.BELONGTO;


-- ERROR 1: FACULTYID in PASSENGER table but not in FACULTY table
    
    -- DATA EXPLORATION (BEFORE): check for PASSENGER with invalid FACULTYID
    SELECT * 
    FROM MONCITY.PASSENGER
    WHERE FACULTYID NOT IN (
        SELECT FACULTYID
        FROM MONCITY.FACULTY
    ); -- Passenger U163 has a invalid FacultyID 

    -- DROP & CREATE TABLE: create a copy of MONCITY.PASSENGER
    DROP TABLE PASSENGER CASCADE CONSTRAINTS PURGE;
    CREATE TABLE PASSENGER AS
    SELECT *
    FROM MONCITY.PASSENGER;

    -- DATA CLEANING: remove the PASSENGER with invalid FACULTYID
    DELETE FROM PASSENGER
    WHERE PASSENGERID = 'U163';

    -- DATA EXPLORATION (AFTER): check that the invalid PASSENGER is safely removed
    SELECT * FROM PASSENGER
    WHERE PASSENGERID = 'U163';



-- ERROR 2: Duplicate BOOKINGID in BOOKING table

    -- DATA EXPLORATION (BEFORE): check for duplicate BOOKINGID in BOOKING table
    SELECT COUNT(*) AS TOTAL_BOOKINGS, COUNT(DISTINCT BOOKINGID) AS TOTAL_VALID_BOOKINGS
    FROM MONCITY.BOOKING;
    -- 10001 record in total, but only 10000 valid BOOKINGID

    SELECT BOOKINGID, REGISTRATIONNO, BOOKINGDATE, PASSENGERID, 
            COUNT(*) AS NUM_OF_RECORDS
    FROM MONCITY.BOOKING 
    GROUP BY BOOKINGID, REGISTRATIONNO, BOOKINGDATE, PASSENGERID
    HAVING COUNT(*) > 1; -- figure which BOOKINGID is duplicate (T1218)

    -- DROP & CREATE TABLE: create a copy of MONCITY.BOOKING
    DROP TABLE BOOKING CASCADE CONSTRAINTS PURGE;
    CREATE TABLE BOOKING AS
    SELECT *
    FROM MONCITY.BOOKING;

    -- DATA CLEANING: remove the BOOKING record with multiple entries, and re-insert it to the table with only one entry
    DELETE FROM BOOKING
    WHERE BOOKINGID = 'T1218';

    INSERT INTO BOOKING (BOOKINGID, REGISTRATIONNO, BOOKINGDATE, DEPARTUREZONE, DESTINATIONZONE, PASSENGERID)
    SELECT DISTINCT BOOKINGID, REGISTRATIONNO, BOOKINGDATE, DEPARTUREZONE, DESTINATIONZONE, PASSENGERID
    FROM MONCITY.BOOKING
    WHERE BOOKINGID = 'T1218';

    -- DATA EXPLORATION (AFTER): check that the duplicate BOOKINGID in BOOKING table is safely removed
    SELECT BOOKINGID, REGISTRATIONNO, BOOKINGDATE, PASSENGERID, 
           COUNT(*) AS NUM_OF_RECORDS
    FROM BOOKING
    GROUP BY BOOKINGID, REGISTRATIONNO, BOOKINGDATE, PASSENGERID
    HAVING COUNT(*) > 1; -- no more duplicate BOOKINGID

    SELECT *
    FROM BOOKING
    WHERE BOOKINGID = 'T1218'; -- ‘T1218’ only left with one record




-- ERROR 3: Negative MAINTENANCECOST in MAINTENANCE table

    -- DATA EXPLORATION (BEFORE): check for negative MAINTENANCECOST in MAINTENANCE table
    SELECT *
    FROM MONCITY.MAINTENANCE
    WHERE MAINTENANCECOST < 0; -- MAINTENANCEID 'M2000' has a negative maintenance cost

    SELECT DISTINCT MAINTENANCETYPE, MAINTENANCECOST
    FROM MONCITY.MAINTENANCE
    ORDER BY MAINTENANCETYPE; -- MAINTENANCECOST depends on MAINTENANCETYPE

    -- DROP & CREATE TABLE: create a copy of MONCITY.MAINTENANCE
    DROP TABLE MAINTENANCE CASCADE CONSTRAINTS PURGE;
    CREATE TABLE MAINTENANCE AS
    SELECT *
    FROM MONCITY.MAINTENANCE;

    -- DATA CLEANING: convert the negative MAINTENANCECOST into positive
    UPDATE MAINTENANCE
    SET MAINTENANCECOST = ABS(MAINTENANCECOST)
    WHERE MAINTENANCECOST < 0;

    -- DATA EXPLORATION (AFTER): confirm that negative MAINTENANCECOST is remove
    SELECT * 
    FROM MAINTENANCE
    WHERE MAINTENANCECOST < 0;

    SELECT DISTINCT MAINTENANCETYPE, MAINTENANCECOST
    FROM MAINTENANCE
    ORDER BY MAINTENANCETYPE;



-- ERROR 4: ACCIDENTID is NULL in ACCIDENTINFO table

    -- DATA EXPLORATION (BEFORE): check for NULL ACCIDENTID in ACCIDENTINFO table
    SELECT COUNT(*) AS NO_OF_ACCIDENTS, COUNT(ACCIDENTID) AS NO_OF_VALID_ACCIDENTID
    FROM MONCITY.ACCIDENTINFO;
    -- 994 record in total, only 993 record has valid ACCIDENTID
    
    SELECT *
    FROM MONCITY.ACCIDENTINFO
    WHERE ACCIDENTID IS NULL; -- figure out null record

    -- DROP & CREATE TABLE: create a copy of MONCITY.ACCIDENTINFO
    DROP TABLE ACCIDENTINFO CASCADE CONSTRAINTS PURGE;
    CREATE TABLE ACCIDENTINFO AS 
    SELECT * 
    FROM MONCITY.ACCIDENTINFO;

    -- DATA CLEANING: remove the NULL record
    DELETE FROM ACCIDENTINFO
    WHERE ACCIDENTID IS NULL;

    -- DATA EXPLORATION (AFTER): check that NULL ACCIDENTID record is safely removed
    SELECT *
    FROM ACCIDENTINFO
    WHERE ACCIDENTID IS NULL;



-- ERROR 5: ERRORCODE in ACCIDENTINFO table but not ERROR table

    -- DATA EXPLORATION (BEFORE): check for invalid ERRORCODE in ACCIDENTINFO table
    SELECT * 
    FROM MONCITY.ACCIDENTINFO
    WHERE ERRORCODE NOT IN (
        SELECT ERRORCODE
        FROM MONCITY.ERROR
    ); -- ACCIDENTID A2000 has a non-existent ERRORCODE

    -- DATA CLEANING: delete the row with non-existing ERRORCODE
    DELETE FROM ACCIDENTINFO
    WHERE ERRORCODE NOT IN (
        SELECT ERRORCODE
        FROM MONCITY.ERROR
    );

    -- DATA EXPLORATION (AFTER): check that the non-existing ERRORCODE record is safely removed
    SELECT * 
    FROM ACCIDENTINFO
    WHERE ERRORCODE NOT IN (
        SELECT ERRORCODE
        FROM MONCITY.ERROR
    );

    SELECT *
    FROM ACCIDENTINFO
    WHERE ACCIDENTID = 'A2000';