
-- CARDIM
DROP TABLE CARDIM CASCADE CONSTRAINTS PURGE;
CREATE TABLE CARDIM AS
SELECT REGISTRATIONNO, CARBODYTYPE, NUMSEATS
FROM MONCITY.CAR;

SELECT * FROM CARDIM;


-- FACULTYDIM
DROP TABLE FACULTYDIM CASCADE CONSTRAINTS PURGE;
CREATE TABLE FACULTYDIM AS
SELECT FACULTYID, FACULTYNAME
FROM MONCITY.FACULTY;

SELECT * FROM FACULTYDIM;


-- AGEDIM
DROP TABLE AGEDIM CASCADE CONSTRAINTS PURGE;
CREATE TABLE AGEDIM (
    AGEID    NUMBER(1),
    AGEGROUP VARCHAR2(50),
    DESCRIPTION  VARCHAR(50)
);

INSERT INTO AGEDIM VALUES (1, 'YOUNG ADULTS', '18-35 YEARS OLD');
INSERT INTO AGEDIM VALUES (2, 'MIDDLE-AGED ADULTS', '36-59 YEARS OLD');
INSERT INTO AGEDIM VALUES (3, 'OLD-AGED ADULTS', '60 YEARS OLD AND OLDER');

SELECT * FROM AGEDIM;


-- BOOKINGTIMEDIM
DROP TABLE BOOKINGTIMEDIM CASCADE CONSTRAINTS PURGE;
CREATE TABLE BOOKINGTIMEDIM AS
SELECT DISTINCT
    TO_CHAR(BOOKINGDATE, 'YYYYMM') AS TIMEID,
    TO_CHAR(BOOKINGDATE, 'MM') AS MONTH,
    TO_CHAR(BOOKINGDATE, 'YYYY') AS YEAR
FROM BOOKING;

SELECT * FROM BOOKINGTIMEDIM;


-- MAINTENANCETYPEDIM
DROP TABLE MAINTENANCETYPEDIM CASCADE CONSTRAINTS PURGE;
CREATE TABLE MAINTENANCETYPEDIM AS
SELECT *
FROM MONCITY.MAINTENANCETYPE;

SELECT * FROM MAINTENANCETYPEDIM;


-- RESEARCHCENTERDIM
DROP TABLE RESEARCHCENTERDIM CASCADE CONSTRAINTS PURGE;
CREATE TABLE RESEARCHCENTERDIM AS
SELECT *
FROM MONCITY.RESEARCHCENTER;

SELECT * FROM RESEARCHCENTERDIM;


-- BRIDGETABLEDIM
DROP TABLE BRIDGETABLEDIM CASCADE CONSTRAINTS PURGE;
CREATE TABLE BRIDGETABLEDIM AS
SELECT *
FROM MONCITY.BELONGTO;

SELECT * FROM BRIDGETABLEDIM;


-- MAINTENANCETEAMDIM
DROP TABLE MAINTENANCETEAMDIM CASCADE CONSTRAINTS PURGE;
CREATE TABLE MAINTENANCETEAMDIM AS
SELECT MT.TEAMID, MT.TEAMLEADER, MT.PHONE, 
    ROUND(1/COUNT(B.CENTERID),2) AS WEIGHTFACTOR, -- WEIGHT FACTOR FOR EACH TEAM
    LISTAGG(B.CENTERID, '-') WITHIN GROUP (ORDER BY B.CENTERID) AS RESEARCHCENTERLIST -- A LIST OF RESEARCH CENTER FOR EACH TEAM
FROM MONCITY.MAINTENANCETEAM MT
JOIN MONCITY.BELONGTO B ON MT.TEAMID = B.TEAMID
GROUP BY MT.TEAMID, MT.TEAMLEADER, MT.PHONE;

SELECT * FROM MAINTENANCETEAMDIM;


-- ERRORDIM
DROP TABLE ERRORDIM CASCADE CONSTRAINTS PURGE;
CREATE TABLE ERRORDIM AS
SELECT *
FROM MONCITY.ERROR;

SELECT * FROM ERRORDIM;


-- ACCIDENTZONEDIM
DROP TABLE ACCIDENTZONEDIM CASCADE CONSTRAINTS PURGE;
CREATE TABLE ACCIDENTZONEDIM AS
SELECT DISTINCT ACCIDENTZONE AS ACCIDENTZONE
FROM ACCIDENTINFO;

SELECT * FROM ACCIDENTZONEDIM;


-- DAMAGESEVERITYDIM
DROP TABLE DAMAGESEVERITYDIM CASCADE CONSTRAINTS PURGE;
CREATE TABLE DAMAGESEVERITYDIM AS
SELECT DISTINCT CAR_DAMAGE_SEVERITY AS DAMAGESEVERITY
FROM ACCIDENTINFO;

SELECT * FROM DAMAGESEVERITYDIM; 


-- BOOKINGTEMPFACT
DROP TABLE BOOKINGTEMPFACT CASCADE CONSTRAINTS PURGE;
CREATE TABLE BOOKINGTEMPFACT AS
SELECT B.BOOKINGID, C.REGISTRATIONNO, P.FACULTYID, P.PASSENGERAGE
FROM BOOKING B
JOIN MONCITY.CAR C ON B.REGISTRATIONNO = C.REGISTRATIONNO
JOIN PASSENGER P ON B.PASSENGERID = P.PASSENGERID;

SELECT * FROM BOOKINGTEMPFACT;


ALTER TABLE BOOKINGTEMPFACT ADD (AGEID NUMBER(1));

UPDATE BOOKINGTEMPFACT
SET AGEID = 1
WHERE PASSENGERAGE >= 18 
AND PASSENGERAGE <= 35;

UPDATE BOOKINGTEMPFACT
SET AGEID = 2
WHERE PASSENGERAGE >= 36 
AND PASSENGERAGE <= 59;

UPDATE BOOKINGTEMPFACT
SET AGEID = 3
WHERE PASSENGERAGE >= 60;

SELECT * FROM BOOKINGTEMPFACT;

-- BOOKINGFACT
DROP TABLE BOOKINGFACT CASCADE CONSTRAINTS PURGE;
CREATE TABLE BOOKINGFACT AS
SELECT BT.REGISTRATIONNO, BT.FACULTYID, TO_CHAR(BOOKINGDATE, 'YYYYMM') AS TIMEID, BT.AGEID AS AGEID, COUNT(*) AS NUM_OF_BOOKING
FROM BOOKINGTEMPFACT BT 
JOIN BOOKING B ON BT.BOOKINGID = B.BOOKINGID
GROUP BY BT.REGISTRATIONNO, BT.FACULTYID, TO_CHAR(BOOKINGDATE, 'YYYYMM'), BT.AGEID;

SELECT * FROM BOOKINGFACT;


-- MAINTENANCEFACT
DROP TABLE MAINTENANCEFACT CASCADE CONSTRAINTS PURGE;
CREATE TABLE MAINTENANCEFACT AS
SELECT REGISTRATIONNO, MAINTENANCETYPE, TEAMID, COUNT(*) AS NUM_OF_MAINTENANCE, SUM(MAINTENANCECOST) AS TOTAL_MAINTENANCE_COST
FROM MAINTENANCE
GROUP BY REGISTRATIONNO, MAINTENANCETYPE, TEAMID;

SELECT * FROM MAINTENANCEFACT;


-- ACCIDENTFACT
DROP TABLE ACCIDENTFACT CASCADE CONSTRAINTS PURGE;
CREATE TABLE ACCIDENTFACT AS
SELECT CA.REGISTRATIONNO, AI.ERRORCODE, AI.ACCIDENTZONE, AI.CAR_DAMAGE_SEVERITY AS DAMAGESEVERITY, COUNT(*) AS NUM_OF_ACCIDENT
FROM MONCITY.CARACCIDENT CA
JOIN ACCIDENTINFO AI ON CA.ACCIDENTID = AI.ACCIDENTID
GROUP BY CA.REGISTRATIONNO, AI.ERRORCODE, AI.ACCIDENTZONE, AI.CAR_DAMAGE_SEVERITY;

SELECT * FROM ACCIDENTFACT;