/* ======================================== BASIC ANALYSIS ======================================== */

-- METRIC 1: WHICH CAR BODY TYPE SHOULD BE FURTHER INVESTED IN BASED ON THE BOOKING, MAINTENANCE, AND ACCIDENT RECORDS
SELECT CARBODYTYPE, SUM(NUM_OF_BOOKING) AS TOTAL_BOOKING
FROM CARDIM C 
JOIN BOOKINGFACT BF ON C.REGISTRATIONNO = BF.REGISTRATIONNO
GROUP BY CARBODYTYPE
ORDER BY TOTAL_BOOKING DESC; -- MORE BOOKING = MORE IN DEMAND = SHOULD CONSIDER INVEST MORE

SELECT C.CARBODYTYPE, SUM(MF.NUM_OF_MAINTENANCE) AS TOTAL_MAINTENANCE, SUM(MF.TOTAL_MAINTENANCE_COST) AS TOTAL_MAINTENANCE_COST
FROM CARDIM C 
JOIN MAINTENANCEFACT MF ON C.REGISTRATIONNO = MF.REGISTRATIONNO
GROUP BY CARBODYTYPE
ORDER BY TOTAL_MAINTENANCE_COST DESC;  -- HIGH MAINTENANCE COST = NEED TO CAREFUL CONSIDER BECAUSE THE ULTIMATE GOAL IS ALWAYS TO SAVE COST

SELECT CARBODYTYPE, SUM(NUM_OF_ACCIDENT) AS TOTAL_ACCIDENT
FROM CARDIM C 
JOIN ACCIDENTFACT AF ON C.REGISTRATIONNO = AF.REGISTRATIONNO
GROUP BY CARBODYTYPE
ORDER BY NUM_OF_ACCIDENT DESC; -- TOO MANY ACCIDENT INVOLVE = TOO DANGEROUS


-- METRIC 2: WHICH ERROR CODE HAS CONTRIBUTED TO THE MOST NUMBER OF ACCIDENTS, ETC.
SELECT ERRORCODE, SUM(NUM_OF_ACCIDENT) AS TOTAL_ACCIDENT_PER_ERRORCODE
FROM ACCIDENTFACT AF
GROUP BY ERRORCODE
ORDER BY TOTAL_ACCIDENT_PER_ERRORCODE DESC;




/* ======================================== FURTHER ANALYSIS SECTION 1: VEHICLE TYPE & COST ANALYSIS ======================================== */
SELECT B.CARBODYTYPE, B.TOTAL_BOOKING, M.TOTAL_MAINTENANCE, M.TOTAL_MAINTENANCE_COST,

    -- METRIC 3: MAINTENANCE COST PER TRIP IDENTIFY WHICH CARTYPE COSTS LESS TO MAINTAIN FOR EACH TRIP
    ROUND((M.TOTAL_MAINTENANCE_COST / B.TOTAL_BOOKING),2) AS COSTPERBOOKING,

    -- METRIC 4: BOOKINGS BETWEEN BREAKDOWNS IDENTIFY WHICH CARTYPE REQUIRE LESS MAINTENANCE
    ROUND((B.TOTAL_BOOKING / M.TOTAL_MAINTENANCE),2) AS "BOOKING BETWEEN MAINTENANCE"

FROM (
    SELECT C.CARBODYTYPE, SUM(BF.NUM_OF_BOOKING) AS TOTAL_BOOKING
    FROM CARDIM C 
    JOIN BOOKINGFACT BF ON C.REGISTRATIONNO = BF.REGISTRATIONNO
    GROUP BY C.CARBODYTYPE
) B

JOIN (
    SELECT C.CARBODYTYPE, SUM(MF.NUM_OF_MAINTENANCE) AS TOTAL_MAINTENANCE, SUM(MF.TOTAL_MAINTENANCE_COST) AS TOTAL_MAINTENANCE_COST
    FROM CARDIM C 
    JOIN MAINTENANCEFACT MF ON C.REGISTRATIONNO = MF.REGISTRATIONNO
    GROUP BY CARBODYTYPE
) M ON B.CARBODYTYPE = M.CARBODYTYPE
ORDER BY COSTPERBOOKING ASC;





/* ======================================== FURTHER ANALYSIS SECTION 2: AUTONOMOUS SAFETY & RELIABILITY ANALYSIS ======================================== */
    -- METRIC 5: MAIN ACCIDENT ERRORCODE CAUSES IDENTIFY MOST COMMON CAUSES OF ACCIDENTS
    SELECT E.ERRORCODE, E.ERRORMESSAGE, SUM(AF.NUM_OF_ACCIDENT) AS TOTAL_ACCIDENT,  
        ROUND((SUM(AF.NUM_OF_ACCIDENT) / (
                    SELECT SUM(NUM_OF_ACCIDENT) 
                    FROM ACCIDENTFACT
                    )
                )  * 100, 2
            ) AS "% OF ACCIDENT"
    FROM ACCIDENTFACT AF
    JOIN ERRORDIM E ON AF.ERRORCODE = E.ERRORCODE
    GROUP BY E.ERRORCODE, E.ERRORMESSAGE
    ORDER BY TOTAL_ACCIDENT DESC;


    -- METRIC 6: ACCIDENT SEVERITY IDENTIFY THE SEVERITY OF AN ACCIDENTS AND INVOLCED FOR EACH CARTYPE 
    WITH ACCIDENTAGG AS (
        SELECT C.CARBODYTYPE, AF.DAMAGESEVERITY, SUM(AF.NUM_OF_ACCIDENT) AS TOTAL_ACCIDENT
        FROM ACCIDENTFACT AF
        JOIN CARDIM C ON AF.REGISTRATIONNO = C.REGISTRATIONNO
        GROUP BY C.CARBODYTYPE, AF.DAMAGESEVERITY
    )
    SELECT CARBODYTYPE, DAMAGESEVERITY, TOTAL_ACCIDENT,
        -- FIND THE % OF THE ACCIDENT ACORSS A PARTICULAR CARBODYTYPE
        ROUND((TOTAL_ACCIDENT / SUM(TOTAL_ACCIDENT) OVER (PARTITION BY CARBODYTYPE)) * 100, 2) AS "% OF ACCIDENT"
    FROM ACCIDENTAGG
    ORDER BY CARBODYTYPE, "% OF ACCIDENT" DESC;


    -- METRIC 7: ACCIDENT RISK BY ZONE IDENTIFY THE NUMBER OF TYPE OF ACCIDENT FOR EACH AREA
    SELECT AF.ACCIDENTZONE, E.ERRORCODE, E.ERRORMESSAGE, SUM(AF.NUM_OF_ACCIDENT) AS TOTAL_ACCIDENT
    FROM ACCIDENTFACT AF
    JOIN ERRORDIM E ON AF.ERRORCODE = E.ERRORCODE
    GROUP BY AF.ACCIDENTZONE, E.ERRORCODE, E.ERRORMESSAGE
    ORDER BY AF.ACCIDENTZONE, TOTAL_ACCIDENT DESC;




/* ======================================== FURTHER ANALYSIS SECTION 3: Fleet Usage & Demand Trends ======================================== */
    -- METRIC 8: BOOKINGS BY FACULTY INDENTIFY THE USAGE OF SELF-DRIVING CAR AMONG THE FACULTIES
    SELECT F.FACULTYID, F.FACULTYNAME, SUM(BF.NUM_OF_BOOKING) AS TOTAL_USAGE
    FROM BOOKINGFACT BF
    JOIN FACULTYDIM F ON BF.FACULTYID = F.FACULTYID
    GROUP BY F.FACULTYID, F.FACULTYNAME
    ORDER BY TOTAL_USAGE DESC;


    -- METRIC 9: USAGE BY USER GROUP INDENTIFY THE USAGE OF SELF-DRIVING CAR FOR EACH AGE GROUP OF PASSENGER.
    SELECT A.AGEGROUP, A.DESCRIPTION, SUM(NUM_OF_BOOKING) AS TOTAL_USAGE
    FROM BOOKINGFACT BF
    JOIN AGEDIM A ON BF.AGEID = A.AGEID
    GROUP BY A.AGEID, A.AGEGROUP, A.DESCRIPTION
    ORDER BY TOTAL_USAGE DESC;
    SELECT * FROM AGEDIM;


    -- METRIC 10: DEMAND IDENTFY THE PERIOD OF HIGH DEMAND IN BOOKING THE SELF-DRIVING CAR.
    SELECT 
    COALESCE(B.MONTH, M.MONTH) AS MONTH,
    NVL(B.TOTALBOOKINGS, 0) AS TOTALBOOKINGS,
    NVL(M.TOTALMAINTENANCEEVENTS, 0) AS TOTALMAINTENANCEEVENTS

    FROM 
        (SELECT T.MONTH, SUM(BF.NUM_OF_BOOKING) AS TOTALBOOKINGS
        FROM BOOKINGFACT BF
        JOIN BOOKINGTIMEDIM T ON BF.TIMEID = T.TIMEID
        GROUP BY T.MONTH) B

    JOIN 
        (SELECT TO_CHAR(MN.MAINTENANCEDATE, 'MM') AS MONTH,
                COUNT(*) AS TOTALMAINTENANCEEVENTS
        FROM MONCITY.MAINTENANCE MN
        GROUP BY TO_CHAR(MN.MAINTENANCEDATE, 'MM')) M
    ON B.MONTH = M.MONTH

    ORDER BY MONTH;




/* ======================================== FURTHER ANALYSIS SECTION 4: Team Efficiency Analysis ======================================== */

    -- METRIC 11: Maintenance Cost by Research Center TO SHOW how research centers share maintenance workloads efficiently without double-counting expenses 
    SELECT RC.CenterID, RC.CenterName,
        -- Proportional Cost Allocation
        ROUND(SUM(MF.TOTAL_MAINTENANCE_COST * MT.WEIGHTFACTOR), 2) AS Allocated_Maintenance_Cost
    FROM MAINTENANCEFACT MF
    JOIN MAINTENANCETEAMDIM MT ON MF.TEAMID = MT.TEAMID
    JOIN BRIDGETABLEDIM BD ON MT.TEAMID = BD.TEAMID
    JOIN RESEARCHCENTERDIM RC ON BD.CENTERID = RC.CENTERID
    GROUP BY RC.CenterID, RC.CenterName
    ORDER BY Allocated_Maintenance_Cost DESC;